queue_rules:
  - name: default
    conditions: ["files>=1"]

pull_request_rules:
  - name: Generic rule not in wip
    conditions:
      - -title~=(?i)wip
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
